### ISSUE TITLE
Export with table folders

### ISSUE THREAD

**Issue by ed9** [maxbube/mydumper#212]
When exporting table names that has slashes in them, it fails to create export folders.

Example:

Table name "my/table" would result in error that it fails to create export file.

**Comment by davidducos** [comment]
We can fix this adding a function like this on mydumper:
```
char * strescape (char *raw_filename,gchar *exceptions ){
        char **split = g_strsplit(g_strescape(raw_filename, exceptions), "/", -1);
        char *filename = g_strjoinv("SLASH", split);
        g_strfreev(split);
        return filename;
}
```
So, a table with "my/table" will be saved on disk like "mySLASHtable". But the problem is in myloader, as it loads the table name to execute the DROP TABLE from the filename, which needs to be changed to use the information from the content of "-schema" file.
