### ISSUE TITLE
cmake err

### ISSUE THREAD

**Issue by sunashe** [maxbube/mydumper#22]
$ cmake .
-- Using mysql-config: /data/mysql/base/bin/mysql_config
-- Found MySQL: /data/mysql/base/include, /data/mysql/base/lib/libmysqlclient.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/librt.so;MYSQL_LIBRARIES_atomic-NOTFOUND;/usr/lib/x86_64-linux-gnu/libdl.so

CMake Warning at docs/CMakeLists.txt:9 (message):
  Unable to find Sphinx documentation generator

-- ------------------------------------------------
-- MYSQL_CONFIG = /data/mysql/base/bin/mysql_config
-- CMAKE_INSTALL_PREFIX = /usr/local
-- BUILD_DOCS = ON
-- WITH_BINLOG = OFF
-- RUN_CPPCHECK = OFF
-- Change a values with: cmake -D<Variable>=<Value>
-- ------------------------------------------------
-- 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MYSQL_LIBRARIES_atomic
    linked by target "mydumper" in directory /data/mydumper
    linked by target "myloader" in directory /data/mydumper

-- Configuring incomplete, errors occurred!
See also "/data/mydumper/CMakeFiles/CMakeOutput.log".

why??

**Comment by matikij** [comment]
I did encounter this when trying to build against latest libmysql in Debian. Root cause seems to be that `mysql_config --libs` returns `-latomic` amongst other libs and the custom cmake MySQL module doesn't  deal with this in a sane way. The way I have dealt with it is switching to MariaDB since Debian stretch is going to switch to MariaDB anyway and it turns out that MariaDB's `mysql_config` doesn't return this lib.

See https://bugs.launchpad.net/mydumper/+bug/1639190 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841607 for more detail.

I am not sure that returning `-latomic` is relevant only for Debian or is it something that Oracle brought into MySQL > 5.7 . I guess this will bite the devs sooner or later.

**Comment by matikij** [comment]
so I had to deal with this anyway, because on mips and mipsel archs Debian's MariaDB's `mysql_config` returned `-latomic` (which seems the right thing to do by the way). My trivial patch is available in #35

**Comment by maxbube** [comment]
Hi I added .rpm packages for the latest release you can use those instead of trying to compile. BTW mydumper/myloader in those packages are compiled static againts mysql libs to it will run with any mysql version you could have. just run 

`sudo yum install https://github.com/maxbube/mydumper/releases/download/v0.9.3/mydumper-0.9.3-41.el7.x86_64.rpm `

**Comment by matikij** [comment]
Well, thing is that I am the maintainer of mydumper for Debian, so I need to have it compilable :-)

**Comment by hydrapolic** [comment]
I just ran into this compiling with MariaDB 10.2. Replacing with https://gitlab.kitware.com/cmake/community/wikis/contrib/modules/FindMySQL made it compile again. Maybe switch to this simpler cmake module?

**Comment by hydrapolic** [comment]
https://bugs.launchpad.net/mydumper/+bug/1639190/comments/2

```
Well, after further investigation it seems that the cmake.org module doesn't do the same job as the bundled one does - it only links to libmysqlclient.so and doesn't set MYSQL_CFLAGS. Since the build succeeded without them anyway maybe they are not needed at all ?
```

**Comment by hydrapolic** [comment]
Linux Gentoo bug report: https://bugs.gentoo.org/654314
