### ISSUE TITLE
release signatures

### ISSUE THREAD

**Issue by matikij** [maxbube/mydumper#28]
Please provide GPG signatures for releases so that they can be verified after download.

**Comment by matikij** [comment]
bump

**Comment by maxbube** [comment]
Hi @matikij I will take this in mind for the next release.

**Comment by davidducos** [comment]
@matikij, 

do you have a command to do it? I will be do for next release if you provide the steps. thanks!

**Comment by matikij** [comment]
@davidducos There's a howto in Debian Wiki https://wiki.debian.org/Creating%20signed%20GitHub%20releases - although I am not sure how much up-to-date it is regarding GitHub UI. If it doesn't work for you let me know, will try to assist you.

**Comment by davidducos** [comment]
@matikij, I reviewed the wiki, and I also compared with another git projects like https://github.com/sysown/proxysql/releases. What they are doing, instead of signing the packages, they are publishing the MD5/SHA1/SHA256, which I think is going to be much simpler for me to add to the releases. What do you think about it?

**Comment by davidducos** [comment]
Latest release has the md5, sha1 and sha256 hashes. From now on we are going to keep it for each release.

**Comment by ottok** [comment]
Thanks for publishing the hashes at https://github.com/mydumper/mydumper/releases, but they don't really provide any actual security assurance.

It is good practice in open source projects to publish cryptographic signatures alongside the tarball source releases, so that e.g. Linux distributions and other downstreams can use OpenPGP to verify the authenticity of the imported release.

This is not a hard requirement, just nice to have. Managing OpenPGP keys securely requires some effort. A good guide on the topic can be found at https://github.com/lfit/itpol/blob/master/protecting-code-integrity.md/

Since this issue is already closed, should I open a new one with the same title?
