### ISSUE TITLE
Need help tuning Myloader, taking 6h+ to load ~500GB data

### ISSUE THREAD

**Issue by TomRibuot** [maxbube/mydumper#282]
Good morning,

We're currently using Myloader in production, and it works fine on our smallest databases.
But we recently tried to adapt our dumping/loading process to a bigger, 500GB+ deflated  10GB once dumped and compressed) Mysql Database and Myloader is taking about 6h or more to load the data, which is too long for our needs.

Is there any way to fine tune Myloader, or what system specs are recommended to lower the time to load ?

We're currently running `myloader --host=<hostname> --user=<user> --password=<password> --directory=/srv/mydumper-files/fr/core --queries-per-transaction=50000 --threads=4 --compress-protocol --verbose=3 -B '<db_name>' -o -e 2>/srv/mydumper-files/fr/logs/myloader.log` and our target database has the following parameters : 
```
transaction-isolation=READ-COMMITTED
innodb_log_buffer_size = 256M
innodb_log_file_size = 1G
innodb_buffer_pool_size = 12800M
innodb_io_capacity = 2000
innodb_io_capacity_max = 3000
innodb_read_io_threads = 8
innodb_write_io_threads = 16
innodb_purge_threads = 2
innodb_buffer_pool_instances = 16
innodb_flush_log_at_trx_commit = 0
max_allowed_packet = 900MB
```

**Comment by davidducos** [comment]
Hi @TomRibuot,

Everything will depends, you might need to play with this:
1- are you reaching the max iops that the disk can provide? if you are reaching, then there is nothing that you can do. 
2- Are you using --rows on mydumper? if you do, you should increase the --threads to double the amount of cores or even triple, to see if that reduce the import timings. 
3- you can drop the indexes and create them later
Please, let me know if that helps

**Comment by hanaura26** [comment]
Hi @davidducos 

Thanks for your reply !

1. We aren't reaching the max iops. 
2. We indeed used --rows and tried to load with 16 threads, we have better results but that wasn't enough.
3. It is exactly the reason why **myloader** took so much time. That is about one specific table that contains contraints like this: 
```
  UNIQUE KEY `XXXXX` (`XXXXX`),
  UNIQUE KEY `XXXXX` (`XXXXX`),
  KEY `XXXXX` (`XXXXX`),
  KEY `XXXXX` (`XXXXX`),
  KEY `XXXXX` (`XXXXX`),
  KEY `XXXXX` (`XXXXX`),
  .....)
```

I followed this process to deactivate constraint parameters on our database :
1. use <database>;
2. set **unique_checks**=0;
3. set **foreign_key_checks**=0;
4. myloader command
But it did not work. We think that it is because of MySQL sessions and that we need to use ```set GLOBAL``` command. I also tried to set GLOBAL but we need to allow it from our RDS instance and i don't think this is a best practice.

- Here is our current workaround test: i've deleted these lines above directly from the "XXX-schema.sql.gz" file and it worked better with only 16minutes of loading. 

- My question is: how can i deactivate these constraints from my **myloader** command session ? Do you think that we need to deactivate from the first sql file of our **mydumper** folder?

Thanks in advance !

**Comment by davidducos** [comment]
Hi @hanaura26, 
Ok, so the issue was the index creation. I will be working over myloader to make possible the creation of the table in 2 stages:
1- Loading data 
2- Create indexes
I don't think that this will be ready for release 0.10.3 but it could be for 0.10.5. 
What I recommend to do as a workaround, is what myloader is going to be doing:
1- Execute mydumper as you are doing currently
2- remove the secondary indexes, leave only the primary key or the first unique index on the tables that you consider.
3- Execute myloader 
4- Execute the ALTER TABLE statements to add the indexes.

BTW, there are efforts in the past to implement this, here is an example https://github.com/davidducos/mydumper but it never reaches master. This might be an opportunity to make it possible.

**Comment by david-ducos-percona** [comment]
Hi @hanaura26,
I used the other repository to work on a new branch. You can review it using:
```
git clone https://github.com/maxbube/mydumper.git
git checkout usingFastIndex
cmake .
make
```
You can use the --innodb-optimize-keys in myloader to import the table structure without the indexes and then create the indexes.
Please, test it throughly before consider production ready, this was the initial implementation.

**Comment by hanaura26** [comment]
Hi @david-ducos-percona 
- I've successfuly checkout your project and your branch.
- I've launched the same **myloader** command with --innodb-optimize-keys and it worked perfectly with **55minutes** of loading :tada:.
That's a very practice option because it avoid me to do a lot of shell tricks to store each table in their respective folder and then launch a myloader command per table in a ```for``` loop. 
Also, I had to use **sed** command to change ```binary``` into ```utf8mb4``` before using this new option and it took me a lot of time to **unzip** and **sed** all files. And now i've noticed that it can handle that too.
Thank you this option saves us!

So now i have some errors when myloader try to recreate indexes. Some errors are about ALTER and TRIGGER command that are not allowed for my user. 
And some errors are like this:
```** (myloader:212351): CRITICAL **: 16:26:38.907: Error restoring database.TABLE from file database.TABLE-schema-triggers.sql.gz: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET character_set_client = @PREV_CHARACTER_SET_CLIENT; SET character_set_results' at line 37```

I am going to allow first my user the permissions needed and then see what will be the behavior of myloader about that last error.

**Comment by hanaura26** [comment]
Hi @david-ducos-percona,
The first error related to "access denied" is fixed due to wrong user.
But then I've found another error like this:
```** (myloader:52871): CRITICAL **: 14:07:51.505: Error restoring database.TABLE from file (null): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\x0A ADD  UNIQUE KEY `XXX` (`productDetailsHash`),\x0A,\x0A AD' at line 3 
ALTER TABLE `database`.`TABLE` 
 ADD  UNIQUE KEY `actionHash` (`actionHash`),```

So with a colleague, we spotted that on the '-schema.sql.gz' file already contains a **comma** between each ```KEY INDEXES``` like the example on my last comment 6 days ago. And on the line 630 of your **myloader.c** file, there is a condition that add a supplementary **comma**. Deleting this condition + other lines (622,633) that use the ```first``` variable is way much better. Now i can correctly recreate my indexes with this specific table but i still have other errors on other tables when myloader try to ALTER TABLE:
```** (myloader:121919): CRITICAL **: 09:25:03.071: Error restoring database.TABLE from file (null): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4
ALTER TABLE `database`.`TABLE`
 ADD  KEY `IDX_XXXXXX` (`test_group_id`),

 ADD  KEY `IDX_XXXXXX` (`test_id`),
```

Do you why I have this kind of error ?

**Comment by davidducos** [comment]
Hi @hanaura26, thank you for testing! I had implemented your changes and I also realized that the CONSTRAINT was not included in the list which might be related to your latest issue. 
Could be possible for you to test it again?

**Comment by hanaura26** [comment]
Hi @davidducos,
My pleasure! Works perfectly with your new changes, now it takes much more time because myloader doesn't have so much errors now :laughing:
It is still running since 1:54 am, but it seems to work correctly.
Since the last myloader command, I only have one error about FULLTEXT indexes: 
```
** Message: 16:01:31.363: Thread 15 restoring indexes `database`.`TABLE`

** (myloader:148623): CRITICAL **: 16:01:31.390: Error restoring database.TABLE from file (null): InnoDB presently supports one FULLTEXT index creation at a time 
ALTER TABLE `database`.`TABLE` 
 ADD  FULLTEXT KEY `brandName` (`brandName`),

 ADD  FULLTEXT KEY `name` (`name`)
;
```
But I think it is not critical as it could be for Foreign Keys or UNIQUE Keys indexes so i could let this error happen but still interesting to fix :wink: 
Now problem is that it seems to take a lot of time like when myloader tried to recreate indexes at the same time.

**Comment by hanaura26** [comment]
Hello @davidducos 

Just to summarize my last actions:
- I moved **"\*schema-triggers.sql.gz"** files in another directory to only restore data and schema files because I thought that it could take much longer if **myloader** will trigger at each insert event. So if I am refering to the logs, it took **2hours** and **34minutes** to load data and recreate indexes before shutting the 16 threads down. I started the load at 10:39am and start shutting down threads at 13:13.
```
** Message: 13:13:42.442: Thread 13 restoring indexes `database`.`TABLE`
** Message: 13:13:50.570: Thread 13 shutting down
```
- I noticed that it takes a lot of time when **myloader** shut down the threads but I still don't know why. I started to think that it was because of a particular table that the concerned thread took a lot of time, but not convinced.. And I don't know how to analyze what the actual thread is working on.

**Comment by davidducos** [comment]
Hi @hanaura26, I did a commit which supports multi fulltext index tables, it will divide the alter table in multiple alters which are be executed sequentially per table. I also fixed and removed other things, please test it again if you can.

**Comment by hanaura26** [comment]
Hi @david-ducos-percona,

Sorry for the late response. I tried your last commit but the results were the same. 
So we switched to a new dump process by using RDS Snapshot sharing.
Thanks for your time.

**Comment by davidducos** [comment]
Hi @hanaura26, 

Can you share your table structure, so I can fix the bug? this might help another people... thanks!

**Comment by LakshyAAAgrawal** [comment]
> * set **unique_checks**=0;
> 
> * set **foreign_key_checks**=0;

Hey, is there some way we could do this in mydumper automatically? Using standard mysqldump and mysqlrestore, this can be easily achieved by creating 2 files, pre.sql and post.sql containing the check disable and enable commands respectively, and then:

```
cat pre.sql dump.sql post.sql | mysql ...
```

**Comment by davidducos** [comment]
@LakshyAAAgrawal please follow https://github.com/maxbube/mydumper/pull/370 to accomplish what you want. Sorry that I don't have the proper documentation of how to use config file but that feature is what you are looking for.
