### ISSUE TITLE
Names with dot are incorrectly restored by myloader

### ISSUE THREAD

**Issue by akrus** [maxbube/mydumper#56]
Hi!

Just found a problem when trying to dump/restore a DB host with databases containing dot in their names.

Let's say I have a database called 'db1.project1', inside I have a table 'table'. mydumper will properly dump everything resulting in a file name 'db1.project1.table-schema.sql'.

But when myloader tries to restore such file, it just creates database with name 'db1', not 'db1.project1'.

I think problem is here:
https://github.com/maxbube/mydumper/blob/master/myloader.c#L355

**Comment by maxbube** [comment]
Hi @akrus thanks for the report, this is also related to issue #41 I will review both

**Comment by maxbube** [comment]
Hi @akrus, I tested your code and looks good. But if could add chunks to it would be great.

i.e.

```
** Message: Thread 2 restoring `mysql`.`user` part 0
** Message: Table mysql.user (Thread 2) took 0.001561 seconds
```

should be

`** Message: Table mysql.user part 0 (Thread 2) took 0.001561 seconds`

**Comment by babaorum** [comment]
Just encounter the same issue. Can I be of any help ?

My use case

I have two databases. One without dot let's say `db1` and one with `db1.test`
If i dump `db1` and load it inside `db1.test` it works fine.
But when i dump `db1.test` and try to load it in `db1.test` I get a bunch of errors like duplicate entries for example.

After renaming `db1.test` into `db1test` everything works fine.
A dump of `db1.test` into `db1test` also works. So the problem seems to be the same as the one described above (during the loading part).

**Comment by ssgoburdhun** [comment]
Hello @akrus,

Got the same issue.

What you can do:
1. Import the necessary users separately (pt-show-grants)
2. Edit the "dbname-schema-create.sql" to add backticks surrounding the database name (`) and create all the schema
Edit example:
```
CREATE DATABASE `db1.project1` /*!40100 DEFAULT CHARACTER SET utf8 */;
```
Create example:
```
cat db1.project1-schema-create.sql | mysql
```
3. Launch the import
```
myloader -s "db1.project1" -B "db1.project1" -d . -v 3
```

You can then industrialize these commands if needed.

Hope it helps.
