### ISSUE TITLE
myloader handling or not handling errors?

### ISSUE THREAD

**Issue by wagnerbianchijr** [maxbube/mydumper#58]
@maxbube,

I've started using mydumper on a project with very large tables and when restoring those tables that has many file chunks on disk (I use -r on mydumper), myloader is firing the below messages:

`** (myloader:14957): CRITICAL **: Error restoring sakila.rental from file sakila.rental.00001.sql: Lock wait timeout exceeded; try restarting transaction`

But, instead of cancel the restore, I just let it to complete and I'm seeing no issues on the final results, as the table has the same number of rows as before (this is a test env):

```
MariaDB [(none)]> select count(*) from sakila.rental;
+----------+
| count(*) |
+----------+
|  4061508 |
+----------+
1 row in set (1.92 sec)

[root@mydumper01 mydumper]# myloader -d . -B sakila -t 10 -q 100 -o --verbose 3
** Message: 10 threads created
** Message: Dropping table or view (if exists) `sakila`.`rental`
** Message: Creating table `sakila`.`rental`
** Message: Thread 7 restoring `sakila`.`rental` part 0
** Message: Thread 2 restoring `sakila`.`rental` part 2
** Message: Thread 8 restoring `sakila`.`rental` part 3
** Message: Thread 9 restoring `sakila`.`rental` part 4
** Message: Thread 6 restoring `sakila`.`rental` part 1
** Message: Thread 10 shutting down
** Message: Thread 4 shutting down
** Message: Thread 5 shutting down
** Message: Thread 3 shutting down
** Message: Thread 1 shutting down

** (myloader:14957): CRITICAL **: Error restoring sakila.rental from file sakila.rental.00001.sql: Lock wait timeout exceeded; try restarting transaction
** Message: Thread 6 shutting down
** Message: Thread 9 shutting down
^@** Message: Thread 8 shutting down
** Message: Thread 2 shutting down

** (myloader:14957): CRITICAL **: Error restoring sakila.rental from file sakila.rental.sql: Duplicate entry '1221716' for key 'PRIMARY'
** Message: Thread 7 shutting down

MariaDB [(none)]> select count(*) from sakila.rental;
+----------+
| count(*) |
+----------+
|  4061508 |
+----------+
1 row in set (1.97 sec)

```
Could you tell if it's expected and if https://bugs.launchpad.net/mydumper/+bug/806698 is related to this? Thanks a lot.

**Comment by maxbube** [comment]
Hi @wagnerbianchijr!

You must always check the log or the exit code if you get a CRITICAL or exit code > 0 you must never trust the restore. Im still letting myloader to continue because as being multithreaded its hard to resume but you can still restore after only the failed table/s.

Your case is weird because I can also see a duplicate key, that means a different process were writing to that schema/table. Maybe another restore? That could be the reason you see a full restore because myloader do no retry chunks.

For the Lock wait `-t 10 -q 100` seems excessive to me I would set -q to 10 to reduce contention.

**Comment by wagnerbianchijr** [comment]
Thanks for the comments @maxbube, gracias y quedamos en contacto!
